# Generated by Django 3.1.2 on 2021-09-13 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=2000, verbose_name='トレンドワード')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
            ],
            options={
                'db_table': 'trend',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
    ]
